# Generated by Django 2.2.6 on 2019-11-19 08:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import emp_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leave_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDialCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('iso2', models.CharField(max_length=2)),
                ('country_prefix', models.IntegerField()),
                ('country_name', models.CharField(max_length=50, validators=[emp_app.validators.name_validators])),
            ],
            options={
                'db_table': 'Country_dial_code',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=50, validators=[emp_app.validators.name_validators])),
                ('added_time', models.TimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.TimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('degree_name', models.CharField(max_length=80, validators=[emp_app.validators.name_validators])),
            ],
            options={
                'db_table': 'Degree_Info',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=50, validators=[emp_app.validators.name_validators])),
                ('added_time', models.TimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.TimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('department_name', models.CharField(max_length=60, validators=[emp_app.validators.name_validators])),
            ],
            options={
                'db_table': 'Department_Info',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=50, validators=[emp_app.validators.name_validators])),
                ('added_time', models.TimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.TimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('designation_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Designation_Info',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=50, validators=[emp_app.validators.name_validators])),
                ('added_time', models.TimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.TimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50, validators=[emp_app.validators.name_validators])),
                ('middle_name', models.CharField(max_length=50, null=True, validators=[emp_app.validators.name_validators])),
                ('last_name', models.CharField(max_length=50, validators=[emp_app.validators.name_validators])),
                ('email_id', models.EmailField(max_length=254, unique=True, validators=[emp_app.validators.email_validators])),
                ('aadhar_no', models.IntegerField()),
                ('emp_status', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='documents/%Y/%m/%d/', validators=[emp_app.validators.validate_image_file_extension])),
            ],
            options={
                'db_table': 'Basic_Info',
            },
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_age', models.IntegerField()),
                ('emp_dob', models.DateField()),
                ('hire_date', models.DateField()),
                ('salary', models.FloatField()),
                ('mobile_no', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Invalid Mobile Number', regex='(0|91|\\+91)[6-9]\\d{9}|([6-9]\\d{9})')])),
                ('gender', models.CharField(max_length=60)),
                ('pan_no', models.CharField(max_length=20)),
                ('permanent_address', models.TextField(max_length=400)),
                ('blood_group', models.CharField(max_length=10)),
                ('about_me', models.CharField(max_length=400)),
                ('marital_status', models.CharField(choices=[('M', 'Married'), ('U', 'Unmarried')], max_length=3)),
                ('relieving_date', models.DateField(null=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.CountryDialCode')),
                ('degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Degree')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Department')),
                ('designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Designation')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Employee')),
            ],
            options={
                'db_table': 'Personal_Info',
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=50, validators=[emp_app.validators.name_validators])),
                ('added_time', models.TimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.TimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('emp_type', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Employee_Type',
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=50, validators=[emp_app.validators.name_validators])),
                ('added_time', models.TimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.TimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('job_title', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Job_Info',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=50, validators=[emp_app.validators.name_validators])),
                ('added_time', models.TimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.TimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('location_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=50, validators=[emp_app.validators.name_validators])),
                ('added_time', models.TimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.TimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role_name', models.CharField(max_length=50, validators=[emp_app.validators.name_validators])),
                ('mobile_no', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Invalid Mobile Number', regex='(0|91|\\+91)[6-9]\\d{9}|([6-9]\\d{9})')])),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='SourceOfHire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=50, validators=[emp_app.validators.name_validators])),
                ('added_time', models.TimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.TimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('source_name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'SourceOfHire',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50, validators=[emp_app.validators.name_validators])),
            ],
            options={
                'db_table': 'State',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=50, validators=[emp_app.validators.name_validators])),
                ('added_time', models.TimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.TimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('emp_id', models.IntegerField()),
                ('previous_company', models.CharField(max_length=100, null=True)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.JobTitle')),
            ],
            options={
                'db_table': 'Work_Experience',
            },
        ),
        migrations.CreateModel(
            name='WorkDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_Joining', models.DateField()),
                ('degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Degree')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Department')),
                ('designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Designation')),
                ('emp_Basic_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.EmployeeInfo')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Employee')),
                ('emp_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.EmployeeType')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.JobTitle')),
                ('location_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Location')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.SourceOfHire')),
            ],
            options={
                'db_table': 'Work_Details',
            },
        ),
        migrations.CreateModel(
            name='ManagerEmpLeaveStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_status_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_app.LeaveStatus')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Employee')),
                ('leave_balance_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_app.LeaveBalance')),
                ('leave_request_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_app.LeaveRequest')),
                ('leave_type_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_app.LeaveType')),
            ],
            options={
                'db_table': 'EmpLeave',
            },
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='emp_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.EmployeeType'),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.JobTitle'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=50, validators=[emp_app.validators.name_validators])),
                ('added_time', models.TimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_time', models.TimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_completion', models.DateField()),
                ('field', models.CharField(max_length=50)),
                ('additional_notes', models.CharField(max_length=60)),
                ('degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Degree')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Employee')),
            ],
            options={
                'db_table': 'Education',
            },
        ),
    ]
